#pragma checksum "C:\Users\Alexander\Documents\GitHub\OneAppAway\OneAppAway\OneAppAway\StopViewPage.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "AE7A0D4B59EB88011552290E9390C79F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneAppAway
{
    partial class StopViewPage : 
        global::OneAppAway.NavigationFriendlyPage, 
        global::Windows.UI.Xaml.Markup.IComponentConnector,
        global::Windows.UI.Xaml.Markup.IComponentConnector2
    {
        /// <summary>
        /// Connect()
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Connect(int connectionId, object target)
        {
            switch(connectionId)
            {
            case 1:
                {
                    this.MainGrid = (global::Windows.UI.Xaml.Controls.Grid)(target);
                    #line 10 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.Grid)this.MainGrid).SizeChanged += this.MainGrid_SizeChanged;
                    #line default
                }
                break;
            case 2:
                {
                    this.MainAppBar = (global::Windows.UI.Xaml.Controls.CommandBar)(target);
                }
                break;
            case 3:
                {
                    global::Windows.UI.Xaml.Controls.AppBarButton element3 = (global::Windows.UI.Xaml.Controls.AppBarButton)(target);
                    #line 85 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarButton)element3).Click += this.RefreshButton_Click;
                    #line default
                }
                break;
            case 4:
                {
                    this.ArrivalsToggle = (global::Windows.UI.Xaml.Controls.AppBarToggleButton)(target);
                    #line 86 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.ArrivalsToggle).Checked += this.AppBarToggleButton_CheckedChanged;
                    #line 86 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.ArrivalsToggle).Unchecked += this.AppBarToggleButton_CheckedChanged;
                    #line default
                }
                break;
            case 5:
                {
                    this.ScheduleToggle = (global::Windows.UI.Xaml.Controls.AppBarToggleButton)(target);
                    #line 91 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.ScheduleToggle).Checked += this.AppBarToggleButton_CheckedChanged;
                    #line 91 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.ScheduleToggle).Unchecked += this.AppBarToggleButton_CheckedChanged;
                    #line default
                }
                break;
            case 6:
                {
                    this.RoutesToggle = (global::Windows.UI.Xaml.Controls.AppBarToggleButton)(target);
                    #line 96 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.RoutesToggle).Checked += this.AppBarToggleButton_CheckedChanged;
                    #line 96 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.AppBarToggleButton)this.RoutesToggle).Unchecked += this.AppBarToggleButton_CheckedChanged;
                    #line default
                }
                break;
            case 7:
                {
                    this.InnerGrid = (global::Windows.UI.Xaml.Controls.Grid)(target);
                    #line 16 "..\..\..\StopViewPage.xaml"
                    ((global::Windows.UI.Xaml.Controls.Grid)this.InnerGrid).SizeChanged += this.InnerGrid_SizeChanged;
                    #line default
                }
                break;
            case 8:
                {
                    this.ArrivalsColumn = (global::Windows.UI.Xaml.Controls.ColumnDefinition)(target);
                }
                break;
            case 9:
                {
                    this.ScheduleColumn = (global::Windows.UI.Xaml.Controls.ColumnDefinition)(target);
                }
                break;
            case 10:
                {
                    this.RoutesColumn = (global::Windows.UI.Xaml.Controls.ColumnDefinition)(target);
                }
                break;
            case 11:
                {
                    this.MainMap = (global::Windows.UI.Xaml.Controls.Maps.MapControl)(target);
                }
                break;
            case 12:
                {
                    this.LastRefreshBox = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            case 13:
                {
                    this.ArrivalsProgressIndicator = (global::Windows.UI.Xaml.Controls.ProgressRing)(target);
                }
                break;
            case 14:
                {
                    this.MainScheduleBrowser = (global::OneAppAway.ScheduleBrowser)(target);
                }
                break;
            case 15:
                {
                    this.ScheduleProgressIndicator = (global::Windows.UI.Xaml.Controls.ProgressRing)(target);
                }
                break;
            case 16:
                {
                    this.RoutesProgressIndicator = (global::Windows.UI.Xaml.Controls.ProgressRing)(target);
                }
                break;
            case 17:
                {
                    this.RoutesControl = (global::Windows.UI.Xaml.Controls.ItemsControl)(target);
                }
                break;
            case 18:
                {
                    this.ArrivalsStackPanel = (global::Windows.UI.Xaml.Controls.StackPanel)(target);
                }
                break;
            case 19:
                {
                    this.DirectionImage = (global::Windows.UI.Xaml.Controls.Image)(target);
                }
                break;
            case 20:
                {
                    this.TitleBlock = (global::Windows.UI.Xaml.Controls.TextBlock)(target);
                }
                break;
            default:
                break;
            }
            this._contentLoaded = true;
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Windows.UI.Xaml.Build.Tasks"," 14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Windows.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
        {
            global::Windows.UI.Xaml.Markup.IComponentConnector returnValue = null;
            return returnValue;
        }
    }
}

